service: serverless-container
# We are using aws as a provider in the N. Virginia region (us-east-1) and defined our stage as project
provider:
  name: aws
  stage: project
  region: us-east-1
  ecr:
    images:
      saveImage:
        path: ./
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:PutObjectAcl
      Resource: "arn:aws:s3:::${self:custom.bucket}/*"
custom:
  bucket: ${self:service}-${self:provider.stage}-demo-jigsawlabs
functions:
  save:
    image:
      name: saveImage
    environment:
      BUCKET: ${self:custom.bucket} 
resources:
  Resources:
    S3Assets:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucket}